
package com.flightprovidera.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.2
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "FlightSearchSOAPImplService", targetNamespace = "http://service.flightprovidera.com/", wsdlLocation = "http://localhost:8080/FlightSearchSOAP?wsdl")
public class FlightSearchSOAPImplService
    extends Service
{

    private final static URL FLIGHTSEARCHSOAPIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException FLIGHTSEARCHSOAPIMPLSERVICE_EXCEPTION;
    private final static QName FLIGHTSEARCHSOAPIMPLSERVICE_QNAME = new QName("http://service.flightprovidera.com/", "FlightSearchSOAPImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/FlightSearchSOAP?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FLIGHTSEARCHSOAPIMPLSERVICE_WSDL_LOCATION = url;
        FLIGHTSEARCHSOAPIMPLSERVICE_EXCEPTION = e;
    }

    public FlightSearchSOAPImplService() {
        super(__getWsdlLocation(), FLIGHTSEARCHSOAPIMPLSERVICE_QNAME);
    }

    public FlightSearchSOAPImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FLIGHTSEARCHSOAPIMPLSERVICE_QNAME, features);
    }

    public FlightSearchSOAPImplService(URL wsdlLocation) {
        super(wsdlLocation, FLIGHTSEARCHSOAPIMPLSERVICE_QNAME);
    }

    public FlightSearchSOAPImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FLIGHTSEARCHSOAPIMPLSERVICE_QNAME, features);
    }

    public FlightSearchSOAPImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FlightSearchSOAPImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FlightSearchSOAP
     */
    @WebEndpoint(name = "FlightSearchSOAPImplPort")
    public FlightSearchSOAP getFlightSearchSOAPImplPort() {
        return super.getPort(new QName("http://service.flightprovidera.com/", "FlightSearchSOAPImplPort"), FlightSearchSOAP.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FlightSearchSOAP
     */
    @WebEndpoint(name = "FlightSearchSOAPImplPort")
    public FlightSearchSOAP getFlightSearchSOAPImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.flightprovidera.com/", "FlightSearchSOAPImplPort"), FlightSearchSOAP.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FLIGHTSEARCHSOAPIMPLSERVICE_EXCEPTION!= null) {
            throw FLIGHTSEARCHSOAPIMPLSERVICE_EXCEPTION;
        }
        return FLIGHTSEARCHSOAPIMPLSERVICE_WSDL_LOCATION;
    }

}
