
package com.flightprovidera.service;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "FlightSearchSOAP", targetNamespace = "http://service.flightprovidera.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FlightSearchSOAP {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.flightprovidera.service.SearchResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "availabilitySearch", targetNamespace = "http://service.flightprovidera.com/", className = "com.flightprovidera.service.AvailabilitySearch")
    @ResponseWrapper(localName = "availabilitySearchResponse", targetNamespace = "http://service.flightprovidera.com/", className = "com.flightprovidera.service.AvailabilitySearchResponse")
    @Action(input = "http://service.flightprovidera.com/FlightSearchSOAP/availabilitySearchRequest", output = "http://service.flightprovidera.com/FlightSearchSOAP/availabilitySearchResponse")
    public SearchResult availabilitySearch(
        @WebParam(name = "arg0", targetNamespace = "")
        SearchRequest arg0);

}
